SUPABASE_URL=<YOUR URL HERE>
SUPABASE_ANON_KEY=<YOUR KEY HERE>
SUPABASE_BUCKET=<YOUR BUCKET NAME HERE>
SUPABASE_IMAGE_PATH=<YOUR PATH TO THE IMAGE HERE>

AP_SSID = "Box"
AP_PASSWORD = "wifiportal"
AP_MDNS_HOSTNAME = "box"